name: build

on:
  push:
  pull_request:

jobs:
  build-all-protocols:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get build-dep -y pidgin

      - name: Configure
        run: |
          ./configure \
            --disable-gtkui \
            --disable-consoleui \
            --disable-perl \
            --disable-tcl \
            --disable-tk \
            --disable-dbus \
            --disable-nm \
            --disable-vv \
            --disable-gstreamer \
            --with-dynamic-prpls=all

      - name: Build
        run: make -j"$(nproc)"
